name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  test:
    name: Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests, generate coverage and JUnit report
        run: npm run test:junit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./frontend/coverage
          flags: frontend
          fail_ci_if_error: false

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run build
        run: npm run build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Check bundle size
        run: |
          BUILD_SIZE=$(du -sb dist | cut -f1)
          GZIP_SIZE=$(find dist -name "*.js" -o -name "*.css" | xargs gzip -c | wc -c)
          echo "Build size: $BUILD_SIZE bytes"
          echo "Gzipped JS/CSS: $GZIP_SIZE bytes"
          # Updated to 115KB (117760 bytes) to account for PWA overhead - Issue #26 final implementation
          # Core app: ~103KB + PWA infrastructure: ~12KB = 115KB total
          if [ "$GZIP_SIZE" -gt 117760 ]; then
            echo "Bundle size exceeds 115KB limit (includes PWA overhead)"
            exit 1
          fi

  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: test
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'pull_request'
    concurrency: deploy-frontend-group
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --app frontend-autumn-brook-1037
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
